name: bank-app-ci

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Test@123
          MYSQL_DATABASE: bankappdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -pTest@123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      
      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL..."
          for i in {1..30}; do
            if mysqladmin ping -h127.0.0.1 -uroot -pTest@123 --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Still waiting..."
            sleep 2
          done

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Unit tests
        run: mvn test

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: bankapp-jar
          path: target/*.jar


  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run Checkstyle 
        run: mvn checkstyle:check 


  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: bankapp-jar
          path: target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/blue-green-deployment:${{ github.run_id }}


  updatek8s:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update tag in Kubernetes manifest
        run: | 
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/blue-green-deployment:${{ github.run_id }}|" k8s/*.yml

      - name: Commit and push changes
        run: |
          git config --global user.email "malimansur11@gmail.com"
          git config --global user.name "Ali Mansur"
          git add .
          git commit -m "[CI]: Update bank app image tag"
          git push origin HEAD:main -f
